import { GenreDefinition, ArtStyleDefinition, Character, StoryBook } from '../types';

export const GENRE_PRESETS: GenreDefinition[] = [
  {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    tagline: 'High-tech rain, low-life alleys, and sentient chrome.',
    description: 'Dystopian megacities illuminated by holographic billboards, rogue neural implants, and corporate conspiracies.',
    iconName: 'Cpu',
    themeColor: 'from-cyan-500 to-fuchsia-500',
    defaultTone: 'gritty_noir',
    samplePromptSeed: 'A data smuggler discovers an encrypted soul trapped inside a black-market memory shard.',
  },
  {
    id: 'fantasy',
    name: 'High Fantasy & Myth',
    tagline: 'Ancient covenants, starlight sorcery, and forgotten realms.',
    description: 'Towering spires, primeval forests whispered into being, and relics that alter the fabric of destiny.',
    iconName: 'Sparkles',
    themeColor: 'from-amber-400 to-emerald-500',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'The last celestial archivist must protect an unwritten constellation from being erased by the Eclipse Guild.',
  },
  {
    id: 'cozy_mystery',
    name: 'Cozy Arcane Mystery',
    tagline: 'Herbal tea, rain on cobblestones, and perplexing clues.',
    description: 'Charming bookshops, eccentric townsfolk, magical familiars, and enigmatic crimes solved with clever deduction.',
    iconName: 'Search',
    themeColor: 'from-amber-600 to-orange-400',
    defaultTone: 'whimsical',
    samplePromptSeed: 'An antique clock in a quiet seaside bakery strikes thirteen, and a customer disappears without leaving footprints.',
  },
  {
    id: 'cosmic_horror',
    name: 'Cosmic & Eldritch Mystery',
    tagline: 'Forbidden geometries, whispered secrets, and abyssal tides.',
    description: 'Scholars uncovering unnamable truths at the edge of comprehension, coastal fog, and eldritch relics.',
    iconName: 'Eye',
    themeColor: 'from-purple-900 to-emerald-900',
    defaultTone: 'psychological_suspense',
    samplePromptSeed: 'A deep-sea oceanographer translates a rhythm vibrating through submarine titanium cables.',
  },
  {
    id: 'steampunk',
    name: 'Steampunk Aeronautics',
    tagline: 'Brass gears, cloud-dock leviathans, and clockwork alchemy.',
    description: 'Soaring airships above chimney-crested skylines, pressure-powered prosthetics, and daring sky explorers.',
    iconName: 'Compass',
    themeColor: 'from-amber-700 to-yellow-600',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'A rogue aeronaut engineer finds a perpetual-motion core inside a grounded sky pirate flagship.',
  },
  {
    id: 'noir',
    name: 'Shadow Noir Detective',
    tagline: 'Venetian blinds, wet asphalt, and cigarette-smoke monologues.',
    description: 'Morally gray private eyes, smoky jazz parlors, rain-slicked boulevards, and cases where everyone has a motive.',
    iconName: 'Glasses',
    themeColor: 'from-zinc-700 to-stone-900',
    defaultTone: 'gritty_noir',
    samplePromptSeed: 'A private detective receives a retainer envelope containing a photograph of himself entering a murder scene he never visited.',
  },
  {
    id: 'solarpunk',
    name: 'Solarpunk Renaissance',
    tagline: 'Living architecture, symbiotic tech, and golden dawn.',
    description: 'Bioluminescent canopies, community glasshouses, clean energy harmony, and journeys of rediscovery.',
    iconName: 'Sun',
    themeColor: 'from-emerald-400 to-teal-500',
    defaultTone: 'heartwarming',
    samplePromptSeed: 'A botanical terraformer unearths a dormant seed vault beneath the roots of an ancient skyscraper.',
  },
  {
    id: 'fairytale',
    name: 'Dark & Whimsical Fairytale',
    tagline: 'Fae bargains, bramble towers, and enchanted mirrors.',
    description: 'Old-world folklore, trickster foxes, cursed glass slippers, and bittersweet bargains under the harvest moon.',
    iconName: 'Moon',
    themeColor: 'from-rose-400 to-purple-600',
    defaultTone: 'poetic_lyrical',
    samplePromptSeed: 'A clockmaker trades their own shadow for seven days of flawless craftsmanship, only to see the shadow start its own life.',
  },
  {
    id: 'space_opera',
    name: 'Grand Space Opera',
    tagline: 'Dyson spheres, interstellar empires, and quantum pilots.',
    description: 'Nebula dogfights, ancient alien gates, planetary courts, and the crew of an independent warp cruiser.',
    iconName: 'Rocket',
    themeColor: 'from-indigo-600 to-blue-400',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'A salvage crew boards a ghost dreadnought drifting between galaxies and triggers its sentient hyperspace navigation core.',
  },
  {
    id: 'gothic_romance',
    name: 'Gothic Manor Romance',
    tagline: 'Crumbling gargoyles, candlelit halls, and secret lineages.',
    description: 'Windswept moors, locked observatory towers, brooding lords, and dangerous love woven with historical secrets.',
    iconName: 'Flame',
    themeColor: 'from-rose-900 to-slate-900',
    defaultTone: 'poetic_lyrical',
    samplePromptSeed: 'An archivist hired to catalogue Blackthorn Manor finds letters addressed to them in handwriting matching their own.',
  },
  {
    id: 'magical_animals',
    name: 'Magical Animal Friends',
    tagline: 'Talking foxes, wise barn owls, and cozy woodland dens.',
    description: 'Charming forest adventures where woodland creatures solve gentle problems and discover magical secrets.',
    iconName: 'Sparkles',
    themeColor: 'from-amber-400 to-emerald-400',
    defaultTone: 'whimsical',
    samplePromptSeed: 'A little red squirrel discovers a miniature golden violin hidden inside a hollow chestnut tree.',
  },
  {
    id: 'bedtime_lullaby',
    name: 'Cozy Bedtime Adventures',
    tagline: 'Starlit clouds, sleepy boats, and sweet goodnights.',
    description: 'Gentle, soothing night-time journeys designed to inspire wonder, calm busy minds, and guide into peaceful sleep.',
    iconName: 'Moon',
    themeColor: 'from-indigo-400 to-purple-400',
    defaultTone: 'gentle_bedtime',
    samplePromptSeed: 'A sleepy baby moonbeam helps a lost cloudling find its way home across the velvet night sky.',
  },
  {
    id: 'kid_detective',
    name: 'Junior Secret Investigators',
    tagline: 'Magnifying glasses, treehouse clubhouses, and neighborhood clues.',
    description: 'Clever mysteries solved through kindness, curiosity, and teamwork with friendly friends and pets.',
    iconName: 'Search',
    themeColor: 'from-sky-400 to-amber-400',
    defaultTone: 'playful_funny',
    samplePromptSeed: 'The mysterious case of the missing blueberry pie from Mrs. Maple’s windowsill on Elm Street.',
  },
  {
    id: 'enchanted_forest',
    name: 'Enchanted Kingdom for Kids',
    tagline: 'Friendly dragons, bouncing pixies, and rainbow bridges.',
    description: 'Magical kingdoms where bravery is kind, giants love gardening, and everyone is invited to the castle feast.',
    iconName: 'Sun',
    themeColor: 'from-rose-400 to-amber-300',
    defaultTone: 'heartwarming',
    samplePromptSeed: 'A tiny dragon who can only breathe bubbles of rainbow light helps light up the village festival.',
  },
];

export const KIDS_MORAL_THEMES = [
  { id: 'kindness', label: 'Kindness & Empathy', description: 'Showing love and consideration to friends and all creatures' },
  { id: 'courage', label: 'Courage & Bravery', description: 'Overcoming fears, trying new things, and standing up for others' },
  { id: 'sharing', label: 'Sharing & Generosity', description: 'Learning the joy of giving, teamwork, and making room for everyone' },
  { id: 'curiosity', label: 'Curiosity & Discovery', description: 'Asking wonderful questions, exploring nature, and loving to learn' },
  { id: 'honesty', label: 'Honesty & Truthfulness', description: 'Being truthful, keeping promises, and building trust' },
  { id: 'nature', label: 'Protecting Nature', description: 'Caring for trees, oceans, animals, and our beautiful planet' },
  { id: 'bedtime_peace', label: 'Peaceful Bedtime & Gratitude', description: 'Celebrating the day’s blessings and resting peacefully' },
];

export const ART_STYLES: ArtStyleDefinition[] = [
  {
    id: 'kids_3d_cartoon',
    name: 'Vibrant 3D Animated Feature',
    description: 'Playful Disney/Pixar style vibrant lighting, expressive characters, smooth textures, joyful and cinematic.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&q=80',
    promptModifier: 'vibrant 3D animated movie style, Pixar Disney aesthetic, cheerful expressive character, soft subsurface scattering, warm volumetric studio lighting, rich colors, 8k render, masterpiece children animation art',
  },
  {
    id: 'cozy_picturebook',
    name: 'Cozy Classic Picture Book',
    description: 'Warm pencil and gouache illustration with gentle woodland charm, Beatrix Potter & Winnie the Pooh aura.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&q=80',
    promptModifier: 'charming classic children book illustration, soft gouache and pencil textures, warm pastel colors, vintage woodland picturebook aesthetic, Beatrix Potter style, heartfelt and wholesome',
  },
  {
    id: 'crayon_papercraft',
    name: 'Playful Crayon & Papercraft',
    description: 'Layered cutout paper craft, vibrant wax crayon accents, handmade texture, pure childhood imagination.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'playful papercraft layered collage illustration with wax crayon details, handmade textured felt and cardboard depth, colorful, whimsical, award winning preschool storybook art',
  },
  {
    id: 'watercolor_storybook',
    name: 'Luminous Storybook Watercolor',
    description: 'Delicate wet-on-wet watercolor washes, gold leaf highlights, soft deckled edges, nostalgic children’s classic aura.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&q=80',
    promptModifier: 'enchanting children book illustration, delicate watercolor wash with gold leaf flecks, dreamy atmospheric lighting, textured paper grain, highly artistic, award winning storybook art',
  },
  {
    id: 'gothic_oil',
    name: 'Gothic Dark Oil Painting',
    description: 'Rich impasto textures, dramatic chiaroscuro Rembrandt lighting, deep crimson & umber tones, painterly classical depth.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=300&q=80',
    promptModifier: 'classical dramatic oil painting on canvas, heavy impasto texture, dark baroque chiaroscuro lighting, deep jewel tones, romantic atmospheric masterpiece',
  },
  {
    id: 'cyber_concept',
    name: 'Neo-Cyber Concept Art',
    description: 'High-contrast neon reflections, volumetric haze, cinematic lens flare, intricate mechanical detail.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'futuristic cinematic concept art, neon rim lighting, volumetric cyan and magenta haze, octane render 8k, matte painting, hyper-detailed cyberpunk aesthetic',
  },
  {
    id: 'vintage_ink',
    name: 'Vintage Woodblock & Quill',
    description: 'Intricate crosshatching, sepia parchment tones, woodcut engraving styling, ancient grimoire feel.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&q=80',
    promptModifier: 'vintage 19th-century woodcut engraving, intricate crosshatching linework, aged parchment sepia palette, Gustave Doré inspired, masterwork ink illustration',
  },
  {
    id: 'studio_anime',
    name: 'Studio Anime Aesthetic',
    description: 'Hand-painted scenic backgrounds, lush cel-shading, emotional character expressions, luminous natural light.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&q=80',
    promptModifier: 'cinematic anime scenic illustration, Studio Ghibli inspired painterly background, warm golden hour illumination, vibrant cel shaded character art, masterpiece',
  },
  {
    id: 'cinematic_realism',
    name: 'Vivid Cinematic Stills',
    description: '35mm anamorphic film grain, dramatic shallow depth of field, naturalistic lighting, photorealistic textures.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&q=80',
    promptModifier: '35mm anamorphic cinematic film still, moody cinematic lighting, shallow depth of field, authentic film grain, photorealistic emotional portrait, 8k resolution',
  },
  {
    id: 'dreamy_pastel',
    name: 'Dreamy Ethereal Pastel',
    description: 'Soft gradient colors, glowing mist, gentle starry aura, whimsical fantasy mood.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'ethereal pastel illustration, soft glowing luminescence, iridescent colors, dreamy floating particles, magical fantasy storybook art',
  },
];

// Initial preset characters with 3D animated Pixar-style children's book aesthetics
export const INITIAL_PRESET_CHARACTERS: Character[] = [
  {
    id: 'preset_char_maya',
    userId: 'default',
    name: 'Maya',
    titleOrRole: 'The Playful Explorer',
    role: 'protagonist',
    gender: 'girl',
    backstory: 'A cheerful, energetic girl full of silly jokes and boundless imagination who brings sunshine into every classroom.',
    personality: ['Playful', 'Joyful', 'Imaginative'],
    flawOrSecret: 'Sometimes gets so excited she forgets to finish her crafts before starting new ones.',
    signatureItem: 'Handmade origami rainbow bird',
    speechPattern: 'Bubbly, energetic, with joyful giggles and playful expressions',
    genreAffinities: ['magical_animals', 'kid_detective', 'enchanted_forest'],
    visualProfile: {
      photoUrl: '/presets/preset_maya.jpg',
      appearanceTags: ['Braided buns', 'Dark brown skin', 'Navy ruffled dress', 'Playful expression', 'Sandals'],
      speciesOrArchetype: 'Pixar 3D Little Explorer',
      artisticStylePrompt: "3D animated Pixar-style children's book character, adorable playful young girl with dark braided buns, dark skin, expressive eyes, navy ruffled sundress in soft magical lighting",
      keyColors: ['#3A506B', '#F5EFEB', '#B45F3C'],
    },
    createdAt: 1700000001,
  },
  {
    id: 'preset_char_zara',
    userId: 'default',
    name: 'Zara',
    titleOrRole: 'The Butterfly Dreamer',
    role: 'companion',
    gender: 'girl',
    backstory: 'Curious and kind-hearted, Zara collects colorful butterfly clips and loves reading about fast cheetahs and magical savannas.',
    personality: ['Curious', 'Gentle', 'Observant'],
    flawOrSecret: 'Worries about making mistakes when speaking up in front of large groups.',
    signatureItem: 'Cheetah graphic t-shirt and pastel butterfly clips',
    speechPattern: 'Warm, thoughtful, asking clever questions about nature and animals',
    genreAffinities: ['magical_animals', 'enchanted_forest', 'bedtime_lullaby'],
    visualProfile: {
      photoUrl: '/presets/preset_zara.jpg',
      appearanceTags: ['Curly afro puffs', 'Pastel butterfly clips', 'Green cheetah tee', 'Dark shorts', 'Green sneakers'],
      speciesOrArchetype: 'Pixar 3D Curious Explorer',
      artisticStylePrompt: "3D animated Pixar-style children's book character, cheerful young girl with curly afro puff adorned with colorful butterfly clips, dark skin, bright smile, green cheetah tee in soft magical lighting",
      keyColors: ['#5B6B56', '#D0A97E', '#4A443F'],
    },
    createdAt: 1700000002,
  },
  {
    id: 'preset_char_kofi',
    userId: 'default',
    name: 'Kofi',
    titleOrRole: 'The Cheerful Storyteller',
    role: 'companion',
    gender: 'boy',
    backstory: 'An enthusiastic big brother and loyal friend who loves inventing games, building treehouses, and encouraging everyone to be brave.',
    personality: ['Enthusiastic', 'Welcoming', 'Courageous'],
    flawOrSecret: 'Tries to carry everyone else’s burdens without asking for help.',
    signatureItem: 'Bright green high-top sneakers and cheetah shirt',
    speechPattern: 'Inspiring, upbeat, greeting everyone with big smiles and open arms',
    genreAffinities: ['kid_detective', 'fantasy', 'enchanted_forest'],
    visualProfile: {
      photoUrl: '/presets/preset_kofi.jpg',
      appearanceTags: ['Short fade hair', 'Warm dark skin', 'Cheetah t-shirt', 'Grey pants', 'Green sneakers'],
      speciesOrArchetype: 'Pixar 3D Big Brother & Friend',
      artisticStylePrompt: "3D animated Pixar-style children's book character, enthusiastic teenage boy with neat fade haircut, beaming smile, open welcoming gestures, green cheetah t-shirt in soft magical storybook lighting",
      keyColors: ['#4A6344', '#78716A', '#F9F7F2'],
    },
    createdAt: 1700000003,
  },
  {
    id: 'preset_char_elena',
    userId: 'default',
    name: 'Ms. Elena',
    titleOrRole: 'The Wise & Caring Guide',
    role: 'mentor',
    gender: 'woman',
    backstory: 'A beloved teacher and storyteller who believes every child holds an infinite universe of creativity and wisdom waiting to bloom.',
    personality: ['Patient', 'Nurturing', 'Wise'],
    flawOrSecret: 'Sometimes misses quiet moments of silence in her bustling world.',
    signatureItem: 'Geometric dangle earrings and classic blue dress',
    speechPattern: 'Gentle, melodious, encouraging, offering comforting pearls of wisdom',
    genreAffinities: ['fairytale', 'magical_animals', 'bedtime_lullaby'],
    visualProfile: {
      photoUrl: '/presets/preset_elena.jpg',
      appearanceTags: ['Wavy brown top bun', 'Hazel eyes', 'Geometric earrings', 'Navy blue dress', 'Warm smile'],
      speciesOrArchetype: 'Pixar 3D Mentor & Teacher',
      artisticStylePrompt: "3D animated Pixar-style children's book character, kind mentor teacher with wavy brown hair in a top bun, gentle smile, geometric earrings, navy blue dress in warm magical classroom lighting",
      keyColors: ['#2E2A27', '#B45F3C', '#EAEFE9'],
    },
    createdAt: 1700000004,
  },
];

export const SAMPLE_INITIAL_BOOKS: StoryBook[] = [];
