import { GenreDefinition, ArtStyleDefinition, Character, StoryBook } from '../types';

export const GENRE_PRESETS: GenreDefinition[] = [
  {
    id: 'cyberpunk',
    name: 'Neon Cyberpunk',
    tagline: 'High-tech rain, low-life alleys, and sentient chrome.',
    description: 'Dystopian megacities illuminated by holographic billboards, rogue neural implants, and corporate conspiracies.',
    iconName: 'Cpu',
    themeColor: 'from-cyan-500 to-fuchsia-500',
    defaultTone: 'gritty_noir',
    samplePromptSeed: 'A data smuggler discovers an encrypted soul trapped inside a black-market memory shard.',
  },
  {
    id: 'fantasy',
    name: 'High Fantasy & Myth',
    tagline: 'Ancient covenants, starlight sorcery, and forgotten realms.',
    description: 'Towering spires, primeval forests whispered into being, and relics that alter the fabric of destiny.',
    iconName: 'Sparkles',
    themeColor: 'from-amber-400 to-emerald-500',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'The last celestial archivist must protect an unwritten constellation from being erased by the Eclipse Guild.',
  },
  {
    id: 'cozy_mystery',
    name: 'Cozy Arcane Mystery',
    tagline: 'Herbal tea, rain on cobblestones, and perplexing clues.',
    description: 'Charming bookshops, eccentric townsfolk, magical familiars, and enigmatic crimes solved with clever deduction.',
    iconName: 'Search',
    themeColor: 'from-amber-600 to-orange-400',
    defaultTone: 'whimsical',
    samplePromptSeed: 'An antique clock in a quiet seaside bakery strikes thirteen, and a customer disappears without leaving footprints.',
  },
  {
    id: 'cosmic_horror',
    name: 'Cosmic & Eldritch Mystery',
    tagline: 'Forbidden geometries, whispered secrets, and abyssal tides.',
    description: 'Scholars uncovering unnamable truths at the edge of comprehension, coastal fog, and eldritch relics.',
    iconName: 'Eye',
    themeColor: 'from-purple-900 to-emerald-900',
    defaultTone: 'psychological_suspense',
    samplePromptSeed: 'A deep-sea oceanographer translates a rhythm vibrating through submarine titanium cables.',
  },
  {
    id: 'steampunk',
    name: 'Steampunk Aeronautics',
    tagline: 'Brass gears, cloud-dock leviathans, and clockwork alchemy.',
    description: 'Soaring airships above chimney-crested skylines, pressure-powered prosthetics, and daring sky explorers.',
    iconName: 'Compass',
    themeColor: 'from-amber-700 to-yellow-600',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'A rogue aeronaut engineer finds a perpetual-motion core inside a grounded sky pirate flagship.',
  },
  {
    id: 'noir',
    name: 'Shadow Noir Detective',
    tagline: 'Venetian blinds, wet asphalt, and cigarette-smoke monologues.',
    description: 'Morally gray private eyes, smoky jazz parlors, rain-slicked boulevards, and cases where everyone has a motive.',
    iconName: 'Glasses',
    themeColor: 'from-zinc-700 to-stone-900',
    defaultTone: 'gritty_noir',
    samplePromptSeed: 'A private detective receives a retainer envelope containing a photograph of himself entering a murder scene he never visited.',
  },
  {
    id: 'solarpunk',
    name: 'Solarpunk Renaissance',
    tagline: 'Living architecture, symbiotic tech, and golden dawn.',
    description: 'Bioluminescent canopies, community glasshouses, clean energy harmony, and journeys of rediscovery.',
    iconName: 'Sun',
    themeColor: 'from-emerald-400 to-teal-500',
    defaultTone: 'heartwarming',
    samplePromptSeed: 'A botanical terraformer unearths a dormant seed vault beneath the roots of an ancient skyscraper.',
  },
  {
    id: 'fairytale',
    name: 'Dark & Whimsical Fairytale',
    tagline: 'Fae bargains, bramble towers, and enchanted mirrors.',
    description: 'Old-world folklore, trickster foxes, cursed glass slippers, and bittersweet bargains under the harvest moon.',
    iconName: 'Moon',
    themeColor: 'from-rose-400 to-purple-600',
    defaultTone: 'poetic_lyrical',
    samplePromptSeed: 'A clockmaker trades their own shadow for seven days of flawless craftsmanship, only to see the shadow start its own life.',
  },
  {
    id: 'space_opera',
    name: 'Grand Space Opera',
    tagline: 'Dyson spheres, interstellar empires, and quantum pilots.',
    description: 'Nebula dogfights, ancient alien gates, planetary courts, and the crew of an independent warp cruiser.',
    iconName: 'Rocket',
    themeColor: 'from-indigo-600 to-blue-400',
    defaultTone: 'epic_heroic',
    samplePromptSeed: 'A salvage crew boards a ghost dreadnought drifting between galaxies and triggers its sentient hyperspace navigation core.',
  },
  {
    id: 'gothic_romance',
    name: 'Gothic Manor Romance',
    tagline: 'Crumbling gargoyles, candlelit halls, and secret lineages.',
    description: 'Windswept moors, locked observatory towers, brooding lords, and dangerous love woven with historical secrets.',
    iconName: 'Flame',
    themeColor: 'from-rose-900 to-slate-900',
    defaultTone: 'poetic_lyrical',
    samplePromptSeed: 'An archivist hired to catalogue Blackthorn Manor finds letters addressed to them in handwriting matching their own.',
  },
  {
    id: 'magical_animals',
    name: 'Magical Animal Friends',
    tagline: 'Talking foxes, wise barn owls, and cozy woodland dens.',
    description: 'Charming forest adventures where woodland creatures solve gentle problems and discover magical secrets.',
    iconName: 'Sparkles',
    themeColor: 'from-amber-400 to-emerald-400',
    defaultTone: 'whimsical',
    samplePromptSeed: 'A little red squirrel discovers a miniature golden violin hidden inside a hollow chestnut tree.',
  },
  {
    id: 'bedtime_lullaby',
    name: 'Cozy Bedtime Adventures',
    tagline: 'Starlit clouds, sleepy boats, and sweet goodnights.',
    description: 'Gentle, soothing night-time journeys designed to inspire wonder, calm busy minds, and guide into peaceful sleep.',
    iconName: 'Moon',
    themeColor: 'from-indigo-400 to-purple-400',
    defaultTone: 'gentle_bedtime',
    samplePromptSeed: 'A sleepy baby moonbeam helps a lost cloudling find its way home across the velvet night sky.',
  },
  {
    id: 'kid_detective',
    name: 'Junior Secret Investigators',
    tagline: 'Magnifying glasses, treehouse clubhouses, and neighborhood clues.',
    description: 'Clever mysteries solved through kindness, curiosity, and teamwork with friendly friends and pets.',
    iconName: 'Search',
    themeColor: 'from-sky-400 to-amber-400',
    defaultTone: 'playful_funny',
    samplePromptSeed: 'The mysterious case of the missing blueberry pie from Mrs. Maple’s windowsill on Elm Street.',
  },
  {
    id: 'enchanted_forest',
    name: 'Enchanted Kingdom for Kids',
    tagline: 'Friendly dragons, bouncing pixies, and rainbow bridges.',
    description: 'Magical kingdoms where bravery is kind, giants love gardening, and everyone is invited to the castle feast.',
    iconName: 'Sun',
    themeColor: 'from-rose-400 to-amber-300',
    defaultTone: 'heartwarming',
    samplePromptSeed: 'A tiny dragon who can only breathe bubbles of rainbow light helps light up the village festival.',
  },
];

export const KIDS_MORAL_THEMES = [
  { id: 'kindness', label: 'Kindness & Empathy', description: 'Showing love and consideration to friends and all creatures' },
  { id: 'courage', label: 'Courage & Bravery', description: 'Overcoming fears, trying new things, and standing up for others' },
  { id: 'sharing', label: 'Sharing & Generosity', description: 'Learning the joy of giving, teamwork, and making room for everyone' },
  { id: 'curiosity', label: 'Curiosity & Discovery', description: 'Asking wonderful questions, exploring nature, and loving to learn' },
  { id: 'honesty', label: 'Honesty & Truthfulness', description: 'Being truthful, keeping promises, and building trust' },
  { id: 'nature', label: 'Protecting Nature', description: 'Caring for trees, oceans, animals, and our beautiful planet' },
  { id: 'bedtime_peace', label: 'Peaceful Bedtime & Gratitude', description: 'Celebrating the day’s blessings and resting peacefully' },
];

export const ART_STYLES: ArtStyleDefinition[] = [
  {
    id: 'kids_3d_cartoon',
    name: 'Vibrant 3D Animated Feature',
    description: 'Playful Disney/Pixar style vibrant lighting, expressive characters, smooth textures, joyful and cinematic.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&q=80',
    promptModifier: 'vibrant 3D animated movie style, Pixar Disney aesthetic, cheerful expressive character, soft subsurface scattering, warm volumetric studio lighting, rich colors, 8k render, masterpiece children animation art',
  },
  {
    id: 'cozy_picturebook',
    name: 'Cozy Classic Picture Book',
    description: 'Warm pencil and gouache illustration with gentle woodland charm, Beatrix Potter & Winnie the Pooh aura.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&q=80',
    promptModifier: 'charming classic children book illustration, soft gouache and pencil textures, warm pastel colors, vintage woodland picturebook aesthetic, Beatrix Potter style, heartfelt and wholesome',
  },
  {
    id: 'crayon_papercraft',
    name: 'Playful Crayon & Papercraft',
    description: 'Layered cutout paper craft, vibrant wax crayon accents, handmade texture, pure childhood imagination.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'playful papercraft layered collage illustration with wax crayon details, handmade textured felt and cardboard depth, colorful, whimsical, award winning preschool storybook art',
  },
  {
    id: 'watercolor_storybook',
    name: 'Luminous Storybook Watercolor',
    description: 'Delicate wet-on-wet watercolor washes, gold leaf highlights, soft deckled edges, nostalgic children’s classic aura.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&q=80',
    promptModifier: 'enchanting children book illustration, delicate watercolor wash with gold leaf flecks, dreamy atmospheric lighting, textured paper grain, highly artistic, award winning storybook art',
  },
  {
    id: 'gothic_oil',
    name: 'Gothic Dark Oil Painting',
    description: 'Rich impasto textures, dramatic chiaroscuro Rembrandt lighting, deep crimson & umber tones, painterly classical depth.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=300&q=80',
    promptModifier: 'classical dramatic oil painting on canvas, heavy impasto texture, dark baroque chiaroscuro lighting, deep jewel tones, romantic atmospheric masterpiece',
  },
  {
    id: 'cyber_concept',
    name: 'Neo-Cyber Concept Art',
    description: 'High-contrast neon reflections, volumetric haze, cinematic lens flare, intricate mechanical detail.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'futuristic cinematic concept art, neon rim lighting, volumetric cyan and magenta haze, octane render 8k, matte painting, hyper-detailed cyberpunk aesthetic',
  },
  {
    id: 'vintage_ink',
    name: 'Vintage Woodblock & Quill',
    description: 'Intricate crosshatching, sepia parchment tones, woodcut engraving styling, ancient grimoire feel.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&q=80',
    promptModifier: 'vintage 19th-century woodcut engraving, intricate crosshatching linework, aged parchment sepia palette, Gustave Doré inspired, masterwork ink illustration',
  },
  {
    id: 'studio_anime',
    name: 'Studio Anime Aesthetic',
    description: 'Hand-painted scenic backgrounds, lush cel-shading, emotional character expressions, luminous natural light.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=300&q=80',
    promptModifier: 'cinematic anime scenic illustration, Studio Ghibli inspired painterly background, warm golden hour illumination, vibrant cel shaded character art, masterpiece',
  },
  {
    id: 'cinematic_realism',
    name: 'Vivid Cinematic Stills',
    description: '35mm anamorphic film grain, dramatic shallow depth of field, naturalistic lighting, photorealistic textures.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&q=80',
    promptModifier: '35mm anamorphic cinematic film still, moody cinematic lighting, shallow depth of field, authentic film grain, photorealistic emotional portrait, 8k resolution',
  },
  {
    id: 'dreamy_pastel',
    name: 'Dreamy Ethereal Pastel',
    description: 'Soft gradient colors, glowing mist, gentle starry aura, whimsical fantasy mood.',
    sampleThumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&q=80',
    promptModifier: 'ethereal pastel illustration, soft glowing luminescence, iridescent colors, dreamy floating particles, magical fantasy storybook art',
  },
];

// Clean slate initial collections (no pre-seeded mock records)
export const INITIAL_PRESET_CHARACTERS: Character[] = [];

export const SAMPLE_INITIAL_BOOKS: StoryBook[] = [];
